# This is a basic workflow to help you get started with Actions

name: CICD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags:
      - v*
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Build:
    # The type of runner that the job will run on
    runs-on: windows-2022

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.x'
      
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Restore NuGet Packages
        run: nuget restore PouleSimulatie.sln
        
      - name: Build Project
        run: msbuild PouleSimulatie.sln /p:Configuration=Release
        
      - name: Upload build artifact
        uses: actions/upload-artifact@v3.x
        with:
          name: BuildArtifact
          path: PouleSimulatie/bin/Release
          
  Zip_and_deploy:
    runs-on: ubuntu-latest
    needs: Build
    steps: 
      - name: Download BuildArtifact
        uses: actions/download-artifact@v4.x
        with:
          name: BuildArtifact
        
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1.0.0
        
      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: ${{steps.tag.outputs.tag}}
          release_name: ${{steps.tag.outputs.tag}}
          draft: false
          prerelease: false
          body_path: ./Changelog.md
          
      - name: Zip the buildfolder
        uses: TonyBogdanov/zip@1.0
        with:
          args: zip -qq -r ./release.zip ./
          
      - name: Upload build assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release.zip
          asset_name: PouleSimulatie.zip
          asset_content_type: application/zip
